#
#  Copyright (c) 2012-2021 Red Hat, Inc.
#    This program and the accompanying materials are made
#    available under the terms of the Eclipse Public License 2.0
#    which is available at https://www.eclipse.org/legal/epl-2.0/
#
#  SPDX-License-Identifier: EPL-2.0
#
#  Contributors:
#    Red Hat, Inc. - initial API and implementation
name: Minikube E2E
on: pull_request
jobs:
  minikube-e2e-olm-rollback:
    name: OLM installer update rollback
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Start minikube cluster
      id: run-minikube
      uses: che-incubator/setup-minikube-action@next
      with:
        minikube-version: v1.21.0
    - name: Install chectl dependencies
      run: yarn
    - name: Install OLM
      run: |
        export OLM_VERSION=v0.17.0
        curl -sL https://github.com/operator-framework/operator-lifecycle-manager/releases/download/${OLM_VERSION}/install.sh | bash -s ${OLM_VERSION}
        sleep 60
    - name: Run OLM e2e rollback tests
      run: |
        export PLATFORM=minikube
        export INSTALLER=olm
        yarn test --coverage=false --forceExit --testRegex=test/e2e/e2e-rollback.test.ts
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: test-artifacts
        path: /tmp/logs/*
