name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Install and Build ðŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          export BEFORE_DEPLOY_DONE=1
          git config --local user.name "Flavius Lacatusu"
          git config --local user.email "flacatus@redhat.com"
          export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')}
          export CHECTL_VERSION="UNKNOWN"
          export GITHUB_RELEASE_NAME=5456weqw

          echo "Branch is master branch..."
          CURRENT_DAY=$(date +'%Y%m%d')
          SHORT_SHA1=$(git rev-parse --short HEAD)
          export CHECTL_VERSION=0.0.$CURRENT_DAY-next
          export GITHUB_RELEASE_NAME=0.0.$CURRENT_DAY-next.$SHORT_SHA1

          sed -i sed "s#version\":\ \"\(.*\)\",#version\":\ \"$CHECTL_VERSION\",#g" package.json
          git tag $TRAVIS_TAG
          TARGETS=linux-arm,linux-x64,linux-s390x,linux-ppc64le,darwin-x64,win32-x64,win32-x86
          npx oclif-dev pack --targets=$TARGETS
          git clone https://github.com/flacatus/chectl -b gh-pages --single-branch gh-pages
          rm -rf gh-pages/.git
          echo $(date +%s) > gh-pages/update
          env

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: gh-pages # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Build"
          files: "./dist/channels/**/chectl-*.gz"