name: Build and Deploy
on:
  # Trigger the workflow on push only for the master branch
  push:
    tags:
      - '7*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
      - uses: actions/setup-node@v1
        with:
          node-version: '10'
      - name: Generate tag utilities
        id: TAG_UTIL
        run: |
          echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
          echo "::set-output name=current_hour::$(date +'%Y%m%d%H%M%S')"
          echo "::set-output name=current_date::$(date +'%Y%m%d')"
      - name: Install and Build ðŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          git config --local user.name "Flavius Lacatusu"
          git config --local user.email "flacatus@redhat.com"

          export CHECTL_VERSION=0.0.${{ steps.TAG_UTIL.outputs.current_date }}-next
          sed -i  "s#version\":\ \"\(.*\)\",#version\":\ \"$CHECTL_VERSION\",#g" package.json

          git tag ${{ steps.TAG_UTIL.outputs.short_sha }}
          yarn
          TARGETS=linux-arm,linux-x64,linux-s390x,linux-ppc64le,darwin-x64,win32-x64,win32-x86
          npx oclif-dev pack --targets=$TARGETS

          git clone https://github.com/flacatus/chectl -b gh-pages --single-branch gh-pages
          rm -rf gh-pages/.git
          echo $(date +%s) > gh-pages/update
          env
      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: gh-pages # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: 0.0.${{ steps.TAG_UTIL.outputs.current_date }}-next.${{ steps.TAG_UTIL.outputs.short_sha }}
          tag_name: ${{ steps.TAG_UTIL.outputs.current_hour }}
          files: "./dist/channels/**/chectl-*.gz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
