name: Build and Deploy
on:
  # Trigger the workflow on push only for the master branch
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
      - uses: actions/setup-node@v1
        with:
          node-version: '10'
      - name: Set short sha
        id: SHA_SHORT
        run: echo "::set-output name=VALUE::$(git rev-parse --short HEAD)"
      - name: Set tag name
        id: TAG
        run: echo "::set-output name=VALUE_TAG::$(date +'%Y%m%d%H%M%S')"
      - name: Set tag name
        id: CURRENT_DATE
        run: echo "::set-output name=VALUE::$(date +'%Y%m%d')"
      - name: Install and Build ðŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          git config --local user.name "Flavius Lacatusu"
          git config --local user.email "flacatus@redhat.com"

          echo "Branch is master branch..."
          git tag ${{ steps.SHA_SHORT.outputs.VALUE }}

          yarn

          TARGETS=linux-arm,linux-x64,linux-s390x,linux-ppc64le,darwin-x64,win32-x64,win32-x86
          npx oclif-dev pack --targets=$TARGETS
          git clone https://github.com/flacatus/chectl -b gh-pages --single-branch gh-pages
          rm -rf gh-pages/.git
          echo $(date +%s) > gh-pages/update
          env

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: gh-pages # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.TAG.outputs.VALUE_TAG }}
          prerelease: false
          title: 0.0.${{ steps.CURRENT_DATE.outputs.VALUE }}-next.${{ steps.SHA_SHORT.outputs.VALUE }}
          files: "./dist/channels/**/chectl-*.gz"
