name: Build and Deploy
on:
  # Trigger the workflow on push only for the master branch
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
      - uses: actions/setup-node@v1
        with:
          node-version: '10'
      - name: Get short sha
        id: SHA_SHORT
        run: echo "::set-output name=VALUE::$(git rev-parse --short HEAD)"
      - name: Set tag name
        id: TAG
        run: echo "::set-output name=VALUE_TAG::$(date +'%Y%m%d%H%M%S')"
      - name: Set current date
        id: CURRENT_DATE
        run: echo "::set-output name=VALUE::$(date +'%Y%m%d')"
      - name: Install and Build ðŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          git config --local user.name "Flavius Lacatusu"
          git config --local user.email "flacatus@redhat.com"
          export CHECTL_VERSION=0.0.${{ steps.CURRENT_DATE.outputs.VALUE }}-next.${{ steps.SHA_SHORT.outputs.VALUE }}
          sed -i  "s#version\":\ \"\(.*\)\",#version\":\ \"$CHECTL_VERSION\",#g" package.json

          git tag ${{ steps.SHA_SHORT.outputs.VALUE }}
          yarn
          TARGETS=linux-arm,linux-x64,linux-s390x,linux-ppc64le,darwin-x64,win32-x64,win32-x86
          npx oclif-dev pack --targets=$TARGETS

          git clone https://github.com/flacatus/chectl -b gh-pages --single-branch gh-pages
          rm -rf gh-pages/.git
          echo $(date +%s) > gh-pages/update
          env
      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: gh-pages # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.TAG.outputs.VALUE_TAG }}
          release_name: 0.0.${{ steps.CURRENT_DATE.outputs.VALUE }}-next.${{ steps.SHA_SHORT.outputs.VALUE }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/channels/next
          asset_content_type: application/gzip
